### ISSUE TITLE
Apk?Image?

### ISSUE THREAD

**Issue by DeLuca92** [bbbalabhaskar/QuickWhatsappSender#1]
This application is for android studio?
It's possible send image?
Or this app use selenium?

**Comment by bbbalabhaskar** [comment]
It is an Android application, under development..

**Comment by DeLuca92** [comment]
Hmm, I will test here.
And try helo u to add new functions :).
What functions works today?

**Comment by bbbalabhaskar** [comment]
This application is basically to provide interface to whatsapp someone who is not in out contact list.  as of today dial screen work and I am working on call logs screen. As I started this for practice you can fork this and play around code as you like. 😄

**Comment by bbbalabhaskar** [comment]
you can use android studio and run this project.
